In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
from sklearn import metrics
import matplotlib.pyplot as plt
import seaborn as sns

# **Part 1 - Data Preprocessing**

**Importing the Dataset**

In [2]:
#https://archive.ics.uci.edu/ml/datasets/Breast+Cancer+Wisconsin+%28Diagnostic%29
df = pd.read_csv('breast_cancer_data.csv', index_col=0)
df  #diagnosis is M for malignant and B for benign

diagnosis  radius_mean  ...  fractal_dimension_worst  Unnamed: 32
id                               ...                                      
842302           M        17.99  ...                  0.11890          NaN
842517           M        20.57  ...                  0.08902          NaN
84300903         M        19.69  ...                  0.08758          NaN
84348301         M        11.42  ...                  0.17300          NaN
84358402         M        20.29  ...                  0.07678          NaN
...            ...          ...  ...                      ...          ...
926424           M        21.56  ...                  0.07115          NaN
926682           M        20.13  ...                  0.06637          NaN
926954           M        16.60  ...                  0.07820          NaN
927241           M        20.60  ...                  0.12400          NaN
92751            B         7.76  ...                  0.07039          NaN

[569 rows x 32 columns]

**Data Cleanup**

In [3]:
df.isnull().sum() #looks like the last column is all null, so lets drop it

diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed: 32                569
dtype: i

In [4]:
df = df.drop(columns=['Unnamed: 32'])
df.head() #removed the last column

diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
id                               ...                                         
842302           M        17.99  ...          0.4601                  0.11890
842517           M        20.57  ...          0.2750                  0.08902
84300903         M        19.69  ...          0.3613                  0.08758
84348301         M        11.42  ...          0.6638                  0.17300
84358402         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

**Separating Inputs and Label**

In [6]:
X = df.iloc[:, 1:].values #take all rows and index columns from 1 to 31
y = df.iloc[:, 0].values #take all rows of column 0 which is the label

print(X)
print(y[0:10])

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
['M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M']


**Encoding the Diagnosis Column**

In [7]:
y[y == 'M'] = 1 #replacing Malignant labels with 1
y[y == 'B'] = 0 #replacing Benign labels with 0

y.dtype #notice datatype is O = object

dtype('O')

In [8]:
y = y.astype(str).astype(int) #converting datatype to int instead
y.dtype

dtype('int64')

**Train Test Split**

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)

X_train

array([[1.026e+01, 1.658e+01, 6.585e+01, ..., 8.333e-02, 2.691e-01,
        9.479e-02],
       [1.989e+01, 2.026e+01, 1.305e+02, ..., 1.613e-01, 2.549e-01,
        9.136e-02],
       [1.120e+01, 2.937e+01, 7.067e+01, ..., 0.000e+00, 1.566e-01,
        5.905e-02],
       ...,
       [1.290e+01, 1.592e+01, 8.374e+01, ..., 1.012e-01, 3.549e-01,
        8.118e-02],
       [1.346e+01, 1.875e+01, 8.744e+01, ..., 1.427e-01, 3.518e-01,
        8.665e-02],
       [1.131e+01, 1.904e+01, 7.180e+01, ..., 6.961e-02, 2.400e-01,
        6.641e-02]])

**Feature Scaling**

In [10]:
#so here we're just scaling all our values using the following formula: z = (x - u) / s
#x is the input, u is the mean, s is the standard deviation
#https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html
#we do this because models normally perform better when numerical input variables are scaled to a standard range
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

X_test

array([[ 0.68161291, -0.79797321,  0.58698411, ...,  0.39805397,
        -0.94982578, -0.62618209],
       [-1.81986036,  1.31673647, -1.82268104, ..., -1.74284867,
        -0.01406114, -0.73722526],
       [ 0.72847892,  0.25698943,  0.78220179, ...,  1.46771645,
         0.28584242,  0.7045918 ],
       ...,
       [ 1.51934284,  1.80953081,  1.49941456, ...,  1.2105557 ,
         0.62016114,  0.82144875],
       [ 0.33597609, -0.56353707,  0.33574745, ...,  0.23239827,
         0.87745544,  0.8330763 ],
       [ 0.520511  ,  0.2904803 ,  0.497863  , ...,  0.5905301 ,
         1.82469181,  1.35631636]])

# **Part 2 - Creating and Training the Model**

In [11]:
logreg = LogisticRegression()
logreg.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

# **Part 3 - Evaluating the Model**

In [12]:
pred = logreg.predict(X_test)
pred

array([0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1])

In [13]:
print(classification_report(y_test,pred)) #very good results

              precision    recall  f1-score   support

           0       0.96      1.00      0.98       101
           1       1.00      0.95      0.98        87

    accuracy                           0.98       188
   macro avg       0.98      0.98      0.98       188
weighted avg       0.98      0.98      0.98       188



In [14]:
print(confusion_matrix(y_test,pred)) #misclassified 4 malignant cells as benign, which is very bad false negative since the individual will think they're cancer free
#however we are accurate 98% of the time which is great

[[101   0]
 [  4  83]]
